using AutoMapper;
using GMM.Application.Interfaces.Repositories;
using GMM.Application.Models;
using MediatR;

namespace GMM.Application.Handlers.Queries.NotificationController
{
    public class QueryFindAll : IRequest<List<ModelNotification>>
    {
        public class QueryFindAllHandler : IRequestHandler<QueryFindAll, List<ModelNotification>>
        {
            private readonly IUnitOfWork _unitOfWork;
            private readonly IMapper _mapper;

            public QueryFindAllHandler(IUnitOfWork unitOfWork, IMapper mapper)
            {
                this._unitOfWork = unitOfWork;
                this._mapper = mapper;
            }

            public async Task<List<ModelNotification>> Handle(QueryFindAll request, CancellationToken cancellationToken)
            {
                //var listEntity = await _unitOfWork.Notifications.AsNoTracking().ToListAsync(cancellationToken);
                //if (listEntity == null || listEntity.Count == 0)
                //    throw new ReecException(ReecEnums.Category.PartialContent, ConstantMessage.NotRecords);
                var listEntity = new List<ModelNotification>() {
                 new ModelNotification()
                {
                    IdNotification = Guid.NewGuid(),
                                  MaintenanceNotification= 10000030,
            MaintNotifInternalID= "QM000010000030",
            NotificationText= "Test MRS",
            MaintPriority= 4,
            NotificationType= "Z3",
            NotifProcessingPhase= 1,
            NotifProcessingPhaseDesc= "Pendiente",
            MaintPriorityDesc= "4-bajo",
            CreationDate= Convert.ToDateTime("2022-05-10T00:00:00"),
            LastChangeTime= "PT16H20M56S",
            LastChangeDate= Convert.ToDateTime("2022-05-10T00:00:00"),
            LastChangeDateTime= Convert.ToDateTime("2022-05-10T21:20:56Z"),
            CreationTime= "PT16H16M58S",
            ReportedByUser= "EXT_PROSSI",
            ReporterFullName= "Pedro Rossi",
            PersonResponsible= "",
            MalfunctionEffect= "",
            MalfunctionEffectText= "",
            MalfunctionStartDate= "2022-05-10T00:00:00",
            MalfunctionStartTime= "PT21H16M21S",
            MalfunctionEndDate= "",
            MalfunctionEndTime= "PT00H00M00S",
            MaintNotificationCatalog= "D",
            MaintNotificationCode= "",
            MaintNotificationCodeGroup= "",
            CatalogProfile= "1",
            NotificationCreationDate= Convert.ToDateTime("2022-05-10T00:00:00"),
            NotificationCreationTime= "PT21H16M21S",
            NotificationTimeZone= "UTC",
            RequiredStartDate= "2022-05-12T00:00:00",
            RequiredStartTime= "PT21H16M47S",
            RequiredEndDate= "2022-05-15T00:00:00",
            RequiredEndTime= "PT21H16M47S",
            LatestAcceptableCompletionDate= "",
            MaintenanceObjectIsDown= false,
            MaintNotificationLongText= "",
            MaintNotifLongTextForEdit= "",
            TechnicalObject= 10000005,
            TechObjIsEquipOrFuncnlLoc= "EAMS_EQUI",
            TechnicalObjectLabel= 10000005,
            MaintenancePlanningPlant= 1101,
            MaintenancePlannerGroup= "MIM",
            PlantSection= "",
            ABCIndicator= 1,
            SuperiorTechnicalObject= "?0100000000000000181",
            SuperiorTechnicalObjectName= "MOTOR DIESEL PRINCIPAL",
            SuperiorObjIsEquipOrFuncnlLoc= "EAMS_FL",
            SuperiorTechnicalObjectLabel= "F-01-01-04-A09-HT0102.SMOT.SUBMOT.MOTDPR",
            ManufacturerPartTypeName= "",
            TechObjIsEquipOrFuncnlLocDesc= "Equipo",
            FunctionalLocation= "?0100000000000000181",
            FunctionalLocationLabelName= "F-01-01-04-A09-HT0102.SMOT.SUBMOT.MOTDPR",
            TechnicalObjectDescription= "MOTOR DIESEL PRINCIPAL - HT102",
            AssetLocation= "",
            LocationName= "",
            BusinessArea= "",
            CompanyCode= "ANTA",
            TechnicalObjectCategory= "T",
            TechnicalObjectType= "",
            MainWorkCenterPlant= 1101,
            MainWorkCenter= "MECAMIO",
            PlantName= "Mina Yanacancha",
            MaintenancePlannerGroupName= "",
            MaintenancePlant= 1101,
            LocationDescription= "",
            MainWorkCenterText= "TECNICOS DE CAMIONES",
            MainWorkCenterPlantName= "Mina Yanacancha",
            MaintenancePlantName= "Mina Yanacancha",
            PlantSectionPersonRespName= "",
            ABCIndicatorDesc= "Medianamente Crítico",
            PersonResponsibleName= "",
            MaintenanceOrder= 20000021,
            MaintenanceOrderType= "ZCOR",
            ConcatenatedActiveSystStsName= "METR ORAS",
            MaintenanceActivityType= "",
            MaintObjDowntimeDurationUnit= "H",
            MaintObjectDowntimeDuration= 0,
            MaintenancePlan= "",
            MaintenanceItem= "",
            TaskListGroup= "",
            TaskListGroupCounter= "",
            MaintenancePlanCallNumber= 0,
            MaintenanceTaskListType= "",
            TaskList= "",
            NotificationReferenceDate= Convert.ToDateTime("2022-05-10T00:00:00"),
            NotificationReferenceTime= "PT16H20M56S",
            NotificationCompletionDate= "",
            CompletionTime= "PT00H00M00S",
            AssetRoom= "",
            MaintNotifExtReferenceNumber= "",
            MaintNotifRejectionReasonCode= "",
            MaintNotifRejectionRsnCodeTxt= "",
            MaintNotifDetectionCatalog= "",
            MaintNotifDetectionCode= "",
            MaintNotifDetectionCodeText= "",
            MaintNotifDetectionCodeGroup= "",
            MaintNotifDetectionCodeGrpTxt= "",
            MaintNotifProcessPhaseCode= "",
            MaintNotifProcessSubPhaseCode= "",
            EAMProcessPhaseCodeDesc= "",
            EAMProcessSubPhaseCodeDesc= ""
},
                 new ModelNotification()
                {
                    MaintenanceNotification= 10000452,
            MaintNotifInternalID= "QM000010000452",
            NotificationText= "TEST SRV 4620000115-20",
            MaintPriority= 3,
            NotificationType= "MI",
            NotifProcessingPhase= 3,
            NotifProcessingPhaseDesc= "En proceso",
            MaintPriorityDesc= "3-Prox. Oportunidad",
            CreationDate= Convert.ToDateTime("2022-11-30T00:00:00"),
            LastChangeTime= "PT00H06M24S",
            LastChangeDate= Convert.ToDateTime("2022-11-30T00:00:00"),
            LastChangeDateTime= Convert.ToDateTime("2022-11-30T05:06:24Z"),
            CreationTime= "PT00H06M24S",
            ReportedByUser= "",
            ReporterFullName= "",
            PersonResponsible= "",
            MalfunctionEffect= "",
            MalfunctionEffectText= "",
            MalfunctionStartDate= "2022-11-30T00:00:00",
            MalfunctionStartTime= "PT00H05M34S",
            MalfunctionEndDate= "",
            MalfunctionEndTime= "PT00H00M00S",
            MaintNotificationCatalog= "",
            MaintNotificationCode= "",
            MaintNotificationCodeGroup= "",
            CatalogProfile= "ZPM-001",
            NotificationCreationDate= Convert.ToDateTime("2022-11-30T00:00:00"),
            NotificationCreationTime= "PT00H05M34S",
            NotificationTimeZone= "UTC-5",
            RequiredStartDate= "2022-12-14T00:00:00",
            RequiredStartTime= "PT00H06M24S",
            RequiredEndDate= "2022-12-28T00:00:00",
            RequiredEndTime= "PT00H06M24S",
            LatestAcceptableCompletionDate= "",
            MaintenanceObjectIsDown= false,
            MaintNotificationLongText= "",
            MaintNotifLongTextForEdit= "",
            TechnicalObject= 10000005,
            TechObjIsEquipOrFuncnlLoc= "EAMS_EQUI",
            TechnicalObjectLabel= 10000005,
            MaintenancePlanningPlant= 1101,
            MaintenancePlannerGroup= "INS",
            PlantSection= "",
            ABCIndicator= 1,
            SuperiorTechnicalObject= "?0100000000000000181",
            SuperiorTechnicalObjectName= "MOTOR DIESEL PRINCIPAL",
            SuperiorObjIsEquipOrFuncnlLoc= "EAMS_FL",
            SuperiorTechnicalObjectLabel= "F-01-01-04-A09-HT0102.SMOT.SUBMOT.MOTDPR",
            ManufacturerPartTypeName= "",
            TechObjIsEquipOrFuncnlLocDesc= "Equipo",
            FunctionalLocation= "?0100000000000000181",
            FunctionalLocationLabelName= "F-01-01-04-A09-HT0102.SMOT.SUBMOT.MOTDPR",
            TechnicalObjectDescription= "MOTOR DIESEL PRINCIPAL - HT102",
            AssetLocation= "",
            LocationName= "",
            BusinessArea= "",
            CompanyCode= "ANTA",
            TechnicalObjectCategory= "T",
            TechnicalObjectType= "",
            MainWorkCenterPlant= 1101,
            MainWorkCenter= "MECAMIO",
            PlantName= "Mina Yanacancha",
            MaintenancePlannerGroupName= "Instrumentación",
            MaintenancePlant= 1101,
            LocationDescription= "",
            MainWorkCenterText= "TECNICOS DE CAMIONES",
            MainWorkCenterPlantName= "Mina Yanacancha",
            MaintenancePlantName= "Mina Yanacancha",
            PlantSectionPersonRespName= "",
            ABCIndicatorDesc= "Medianamente Crítico",
            PersonResponsibleName= "",
            MaintenanceOrder= 10000104,
            MaintenanceOrderType= "PM01",
            ConcatenatedActiveSystStsName= "METR ORAS",
            MaintenanceActivityType= "",
            MaintObjDowntimeDurationUnit= "H",
            MaintObjectDowntimeDuration= 0,
            MaintenancePlan= "",
            MaintenanceItem= "",
            TaskListGroup= "",
            TaskListGroupCounter= "",
            MaintenancePlanCallNumber= 0,
            MaintenanceTaskListType= "",
            TaskList= "",
            NotificationReferenceDate= Convert.ToDateTime("2022-11-30T00:00:00"),
            NotificationReferenceTime= "PT00H05M34S",
            NotificationCompletionDate= "",
            CompletionTime= "PT00H00M00S",
            AssetRoom= "",
            MaintNotifExtReferenceNumber= "",
            MaintNotifRejectionReasonCode= "",
            MaintNotifRejectionRsnCodeTxt= "",
            MaintNotifDetectionCatalog= "",
            MaintNotifDetectionCode= "",
            MaintNotifDetectionCodeText= "",
            MaintNotifDetectionCodeGroup= "",
            MaintNotifDetectionCodeGrpTxt= "",
            MaintNotifProcessPhaseCode= "",
            MaintNotifProcessSubPhaseCode= "",
            EAMProcessPhaseCodeDesc= "",
            EAMProcessSubPhaseCodeDesc= ""
                 }};
                var result = _mapper.Map<List<ModelNotification>>(listEntity);
                return result;
            }
        }
    }
}
